include:
  - project: 'ci-cd/templates'
    ref: master
    file: '/prodsec/.oss-scan.yml'

default:
  image: cimg/python:3.8

oss-scan:
  stage: lint
  extends: .oss-scan

lint:
  stage: lint
  script: |
    python3 -m venv venv
    . venv/bin/activate
    pip3 install cfn-lint
    cfn-lint **/template_*.yaml

# Disabled "upload-test" as we do not want the AWS RND credentials to be used outside the main branch.
# We can enable this back when we move those credentials to a secret manager (e.g. Hashicorp Vault)

#upload-test: # copy artifacts to S3
#  stage: release
#  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
#  script: |
#    apt-get -y install make
#    export ENV=test && make release-to-env
#  rules:
#    - if: '$CI_COMMIT_BRANCH != "main"'

upload-stage: # replace all /test links with /stage and copy artifacts to S3
  stage: release
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: |
    apt-get -y install make
    export ENV=stage && make release-to-env
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

upload-release: # replace all /test links with /release and copy artifacts to S3 + make them publicly available
  stage: release
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script: |
    apt-get -y install make
    export ENV=release && make release-to-env
  rules:
    - if: '$CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+.*/'

stages:
  - lint
  - release
