version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.4.0

jobs:

  cfn-lint:
    docker:
      - image: circleci/python:3.7.5
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install cfn-lint
          name: install cfn-lint in venv
      - run:
          command: |
            . venv/bin/activate
            cfn-lint **/template_*.yaml
          name: run linter

  release-to-environment:
    executor: aws-cli/default
    parameters:
      environment:
        type: string
        default: "test"
      public:
        type: boolean
        default: false
    steps:
        - aws-cli/setup:
            profile-name: rnd
        - checkout
        - run:
            command: make release-to-env ENV=<< parameters.environment >>
            name: Replace all /test links with /<< parameters.environment >> and release. If env == release, templates will be published.

workflows:
  main:
    jobs:
      - cfn-lint
      - release-to-environment:
          environment: test
          requires:
            - cfn-lint
      - release-to-environment:
          environment: stage
          requires:
            - cfn-lint
          filters:
            branches:
              only: main
            tags:
              ignore: /^\d+\.\d+\.\d+$/
      - release-to-environment:
          environment: release
          requires:
            - cfn-lint
          public: true
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
