#====== DO NOT DEPLOY THIS FILE TO PRODUCTION. =======================================================================================
#====== USE PACKAGED VERSION https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/release/template_all_features.yaml =====
AWSTemplateFormatVersion: '2010-09-09'
Description: Splunk Logs and Metric Streams Integration

Parameters:
  SplunkAPIKey:
    Type: String
    NoEcho: true
    Description: "Splunk Observability Access Token. You should have copied it in the previous step from the integration configuration. You can also find it in Organization Settings --> Access Tokens."
  SplunkIngestUrl:
    Type: String
    Description: "Real-time Data Ingest url can be found in your Profile --> Account Settings --> Endpoints. The field value should follow the pattern: https://ingest.${REALM}.signalfx.com"
  EnabledRegions:
    Type: CommaDelimitedList
    Description: "Comma-delimited list of regions where you want to collect logs and metric streams. For example: \"us-east-1,eu-central-1,ap-south-1\"."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Required Parameters
        Parameters:
          - SplunkAPIKey
          - EnabledRegions
          - SplunkIngestUrl
    ParameterLabels:
      SplunkAPIKey:
        default: "Access Token"
      EnabledRegions:
        default: "Regions to deploy to"
      SplunkIngestUrl:
        default: "Real-time Data Ingest endpoint"

Resources:

  SplunkAwsLogsCollectorRegionalResources:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: SplunkAwsLogsCollectorRegionalResources
      Description: Create regional resources for Splunk AWS Logs Collector
      Capabilities:
        - CAPABILITY_NAMED_IAM
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref EnabledRegions
      Parameters:
        - ParameterKey: SplunkAPIKey
          ParameterValue: !Ref SplunkAPIKey
        - ParameterKey: SplunkIngestUrl
          ParameterValue: !Ref SplunkIngestUrl
      TemplateURL: https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/test/template_logs_regional.yaml

  SplunkMetricStreamsRegionalResources:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: SplunkMetricStreamsRegionalResources
      Description: Create regional resources for Splunk integration with CloudWatch Metric Streams
      Capabilities:
        - CAPABILITY_NAMED_IAM
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref EnabledRegions
      Parameters:
        - ParameterKey: SplunkAPIKey
          ParameterValue: !Ref SplunkAPIKey
        - ParameterKey: SplunkIngestUrl
          ParameterValue: !Ref SplunkIngestUrl
      TemplateURL: https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/test/template_metric_streams_regional.yaml

