#====== DO NOT DEPLOY THIS FILE TO PRODUCTION. =======================================================================================
#====== USE PACKAGED VERSION https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/release/template_all_features_regional.yaml =====

AWSTemplateFormatVersion: '2010-09-09'
Description: Regional resources required by Splunk AWS integration with CloudWatch Metric Streams and logs collection

Parameters:
  SplunkAPIKey:
    Type: String
    NoEcho: true
    Description: "Splunk Observability Access Token. You should have copied it in the previous step from the integration configuration. You can also find it in Organization Settings --> Access Tokens."
  SplunkLogIngestUrl:
    Type: String
    Description: "Real-time Data Ingest url with an additional suffix 'v1/log'. Real-time Data Ingest url can be found in your Profile --> Account Settings --> Endpoints. The field value should follow the pattern: https://ingest.${REALM}.signalfx.com/v1/log"
  SplunkMetricIngestUrl:
    Type: String
    Description: "Real-time Data Ingest url can be found in your Profile --> Account Settings --> Endpoints. The field value should follow the pattern: https://ingest.${REALM}.signalfx.com."
  SplunkCloudIngestUrl:
    Type: String
    Description: "Real-time Data Ingest url with an additional suffix '/v1/cloudwatch_metric_stream'. Real-time Data Ingest url can be found in your Profile --> Account Settings --> Endpoints. The field value should follow the pattern: https://ingest.${REALM}.signalfx.com/v1/cloudwatch_metric_stream."
  UseHostedLambdaDeploymentPackage:
    Type: String
    Default: "true"
    Description: "Change this to false if you are deploying to Gov or China region. That will make it possible for you to pass a custom location of the zip archive in the following parameters."
  LambdaDeploymentPackageS3Bucket:
    Type: String
    Description: "S3 bucket where aws-log-collector lambda deployment package is stored. Must be in the same region as this deployment. You should set this only in Gov and China."
    Default: ""
  LambdaDeploymentPackageS3Key:
    Type: String
    Description: "Aws-log-collector lambda deployment package path (key) in S3. You should set this only in Gov and China."
    Default: ""

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Required Parameters
        Parameters:
          - SplunkAPIKey
          - SplunkMetricIngestUrl
          - SplunkCloudIngestUrl
          - SplunkLogIngestUrl
      -
        Label:
          default: (Optional) Lambda Deployment Package location. You need to modify this section if you're deploying to Gov or China regions.
        Parameters:
          - UseHostedLambdaDeploymentPackage
          - LambdaDeploymentPackageS3Bucket
          - LambdaDeploymentPackageS3Key
    ParameterLabels:
      SplunkAPIKey:
        default: "Access Token"
      SplunkMetricIngestUrl:
        default: "Ingest url"
      SplunkCloudIngestUrl:
        default: "Ingest url followed with log path"
      SplunkLogIngestUrl:
        default: "Ingest url followed with log path"
      UseHostedLambdaDeploymentPackage:
        default: "Use Splunk-hosted archive with lambda code"
      LambdaDeploymentPackageS3Bucket:
        default: "S3Bucket with the archive"
      LambdaDeploymentPackageS3Key:
        default: "Path of the archive in the bucket"

Resources:
  SplunkAwsLogsCollector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3://o11y-public/logs/packaged_logs_regional.test.yaml
      Parameters:
        - ParameterKey: SplunkAPIKey
          ParameterValue: !Ref SplunkAPIKey
        - ParameterKey: SplunkLogIngestUrl
          ParameterValue: !Ref SplunkLogIngestUrl
        - ParameterKey: SplunkMetricIngestUrl
          ParameterValue: !Ref SplunkMetricIngestUrl
        - ParameterKey: LambdaDeploymentPackageS3Bucket
          ParameterValue: !Ref LambdaDeploymentPackageS3Bucket
        - ParameterKey: LambdaDeploymentPackageS3Key
          ParameterValue: !Ref LambdaDeploymentPackageS3Key
        - ParameterKey: UseHostedLambdaDeploymentPackage
          ParameterValue: !Ref UseHostedLambdaDeploymentPackage
  SplunkAwsMetricStreams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: s3://o11y-public/logs/packaged_metric_streams_regional.test.yaml
      Parameters:
        - ParameterKey: SplunkAPIKey
          ParameterValue: !Ref SplunkAPIKey
        - ParameterKey: SplunkCloudIngestUrl
          ParameterValue: !Ref SplunkCloudIngestUrl
