#====== DO NOT DEPLOY THIS FILE TO PRODUCTION. =======================================================================================
#====== USE PACKAGED VERSION https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/release/template_all_features_regional.yaml =====

AWSTemplateFormatVersion: '2010-09-09'
Description: Regional resources required by Splunk AWS integration with CloudWatch Metric Streams and logs collection

Parameters:
  SplunkAccessToken:
    Type: String
    NoEcho: true
    Description: "Copy your Splunk Observability access token with INGEST authorization scope from Settings > Access Tokens."
  SplunkIngestUrl:
    Type: String
    Description: "Find the real-time data ingest endpoint in Settings > Profile > Organizations.."
  RedactionRule:
    Type: String
    Description: "Replace text matching the supplied regular expression with redaction rule replacement."
    Default: ""
  RedactionRuleReplacement:
    Type: String
    Description: "Replace text matching the redaction rule with the following text."
    Default: "**REDACTED**"
  IncludeLogFields:
    Type: String
    Description: "If this is set to \"false\", the function will forward only raw log line from the source. If set to \"true\", the function will forward both the raw log line and fields it parsed out from the line. The default value of \"false\" is meant to reduce log volume"
    Default: "false"
  UseHostedLambdaDeploymentPackage:
    Type: String
    Default: "true"
    Description: "Change this to false if you are deploying to Gov or China regions to pass a custom location of the zip archive in other parameters."
  LambdaDeploymentPackageS3Bucket:
    Type: String
    Description: "Enter the S3 bucket where the aws-log-collector lambda deployment package is stored. It must be in the same region as this deployment. Set the S3 bucket only for Gov and China regions. For example, if the ARN of your archive is \"arn:aws:s3::::my-bucket/my-folder/aws-log-collector.zip\", the value of this parameter is \"my-bucket\"."
    Default: ""
  LambdaDeploymentPackageS3Key:
    Type: String
    Description: "Aws-log-collector lambda deployment package path (key) in S3. Set this only in Gov and China regions. For example, if the ARN of your archive is \"arn:aws:s3::::my-bucket/my-folder/aws-log-collector.zip\", the value of this parameter is \"my-folder/aws-log-collector.zip\"."
    Default: ""

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Required Parameters
        Parameters:
          - SplunkAccessToken
          - SplunkIngestUrl
      -
        Label:
          default: (Optional) Sensitive data redaction
        Parameters:
          - RedactionRule
          - RedactionRuleReplacement
      -
        Label:
          default: (Optional) Additional fields from S3 log files
        Parameters:
          - IncludeLogFields
      -
        Label:
          default: (Optional) Lambda deployment package location. Modify this section if deploying to Gov or China regions.
        Parameters:
          - UseHostedLambdaDeploymentPackage
          - LambdaDeploymentPackageS3Bucket
          - LambdaDeploymentPackageS3Key
    ParameterLabels:
      SplunkAccessToken:
        default: "Access token"
      SplunkIngestUrl:
        default: "Real-time data ingest endpoint"
      RedactionRule:
        default: "Redaction rule"
      RedactionRuleReplacement:
        default: "Redaction rule replacement"
      IncludeLogFields:
        default: "Include log fields"
      UseHostedLambdaDeploymentPackage:
        default: "Use Splunk-hosted archive with lambda code"
      LambdaDeploymentPackageS3Bucket:
        default: "S3 Bucket with the archive"
      LambdaDeploymentPackageS3Key:
        default: "Path of the archive in the bucket"

Resources:
  SplunkAwsLogsCollector:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/test/template_logs_regional.yaml
      Parameters:
        SplunkAccessToken: !Ref SplunkAccessToken
        SplunkIngestUrl: !Ref SplunkIngestUrl
        RedactionRule: !Ref RedactionRule
        RedactionRuleReplacement: !Ref RedactionRuleReplacement
        IncludeLogFields: !Ref IncludeLogFields
        LambdaDeploymentPackageS3Bucket: !Ref LambdaDeploymentPackageS3Bucket
        LambdaDeploymentPackageS3Key: !Ref LambdaDeploymentPackageS3Key
        UseHostedLambdaDeploymentPackage: !Ref UseHostedLambdaDeploymentPackage
  SplunkAwsMetricStreams:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/test/template_metric_streams_regional.yaml
      Parameters:
        SplunkAccessToken: !Ref SplunkAccessToken
        SplunkIngestUrl: !Ref SplunkIngestUrl
