#====== DO NOT DEPLOY THIS FILE. =======================================================================================
#====== USE PACKAGED VERSION https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/release/template_metric_streams_per_account.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Global resources for Splunk AWS Metric Streams Integration.

Resources:
  SplunkMetricStreamsS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'splunk-metric-streams-s3-${AWS::AccountId}'

  SplunkMetricStreamsS3Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: splunk-metric-streams-s3
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - firehose.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: s3_access
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:AbortMultipartUpload'
                  - 's3:GetBucketLocation'
                  - 's3:GetObject'
                  - 's3:ListBucket'
                  - 's3:ListBucketMultipartUploads'
                  - 's3:PutObject'
                Resource: !GetAtt SplunkMetricStreamsS3.Arn
      Description: 'A role that allows Kinesis Firehose to store failed requests in S3'
