#====== DO NOT DEPLOY THIS FILE. =======================================================================================
#====== USE PACKAGED VERSION https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/release/template_metric_streams.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Splunk Metric Streams Integration

Parameters:
  SplunkAccessToken:
    Type: String
    NoEcho: true
    Description: "Copy your Splunk Observability access token from the Observability Cloud AWS integration wizard. You can also find it in Profile > Organization Settings > Access Tokens."
  SplunkIngestUrl:
    Type: String
    Description: "Find the real-time data ingest URL in Profile > Account Settings > Endpoints. Note: do NOT include endpoint path here: for instance use https://ingest.us1.signalfx.com instead of https://ingest.us1.signalfx.com/v1/cloudwatch_metric_stream."
  EnabledRegions:
    Type: CommaDelimitedList
    Description: "Enter a comma-delimited list of regions from which you want to collect metric streams. For example: \"us-east-1,eu-central-1,ap-south-1\"."

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Required Parameters
        Parameters:
          - SplunkAccessToken
          - SplunkIngestUrl
          - EnabledRegions
    ParameterLabels:
      SplunkAccessToken:
        default: "Access token"
      SplunkIngestUrl:
        default: "Real-time data ingest endpoint"
      EnabledRegions:
        default: "Regions to deploy to"

Resources:

  SplunkMetricStreamsRegionalResources:
    Type: AWS::CloudFormation::StackSet
    Properties:
      StackSetName: SplunkMetricStreamsRegionalResources
      Description: Create regional resources for Splunk integration with CloudWatch Metric Streams
      Capabilities:
        - CAPABILITY_NAMED_IAM
      PermissionModel: SELF_MANAGED
      StackInstancesGroup:
        - DeploymentTargets:
            Accounts:
              - !Ref "AWS::AccountId"
          Regions: !Ref EnabledRegions
      Parameters:
        - ParameterKey: SplunkAccessToken
          ParameterValue: !Ref SplunkAccessToken
        - ParameterKey: SplunkIngestUrl
          ParameterValue: !Ref SplunkIngestUrl
      TemplateURL: https://o11y-public.s3.amazonaws.com/aws-cloudformation-templates/test/template_metric_streams_regional.yaml
